# POST http://localhost:3003/api/users
# Content-Type: application/json

# {
#     "name": "test",
#     "username": "test",
#     "password": "test"
# }

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "testtitle",
    "author": "testauthor",
    "url": "https://test.com",
    "likes": 5
}